### PR TITLE
User Interface templates and wireframes

### PR DESCRIPTION
**Pull request by puritysowayi**
**STATUS**
In development
**DESCRIPTION**
This pull request includes styling for the User Interfaces in CSS and Javascript.
The User Interfaces designs display ability to Log in and Register, View, Edit, Delete and Update shopping lists.
Additional folders for the wireframes and UML diagram are available.
**TESTING**
Open the index.html file using a browser to view the designs. Click on the various buttons on the designs to navigate through the designs.

### CODE REVIEW

**Comment by NaomiMariga** [comment]
Have the templates in the designs/UI folders, also, host the project on github pages.

**Comment by thira-lynn** [comment]
The structure is good. 
Kindly include a folder for designs inclusive of the interfaces created and another inclusive of the templates for consistency. And also to enable ease of accessing your work.

**Comment by ghost** [comment]
I was blown away by you pivotal tracker board. You did a stellar job. 

Your commits were very clear and atomic. Your pull request was very well detailed and written. Really like how you indicated the type of task you were working on in some of the commits. However, many of the commits you made lacked a task type. This shows a bit of inconsistency. 

Wait a go on the wireframes,  clearly exceeding expectations. 

Great work on the views, as well as the validation you added in some of the forms. 

A few improvements you could make:
- Deleting the wireframes images from the base of the project
- Moving all your html, css and js files to the Designs folder
- Adding more detail to your README.md so that users would know how to get your app working from them once they clone you repo.

Otherwise great job.

**Comment by ghost** [comment]
Your deployment on Github pages looks amazing :smile:

**Comment by puritysowayi** [comment]
Thank you @NaomiMariga, I have done so.

**Comment by puritysowayi** [comment]
Thanks, @thira-lynn, I've done that.

**Comment by puritysowayi** [comment]
Thank you @hkoske, I'm working on implementing the changes you have suggested.

**Pull request merged**
